### PR TITLE
Java: Rewrite handling of ORTERecvInfo structure in middle-code

### PR DESCRIPTION
**Pull request by Vajnar**
Switch from Thumb to ARM mode for better performance.

### CODE REVIEW

**Comment by wentasah** [comment]
On Wed, Mar 25 2015, Martin Vajnar wrote:
> Switch from Thumb to ARM mode for better performance.

Have you measured how this change influence the performance?

**Comment by Vajnar** [comment]
Rewrite part of the 'middle' subscriber callback function, that is responsible for preparing the 'Received Information' class.

Previously the underlying C structure was parsed every-time new issue arrived and transformed into corresponding Java fields. Now, upon first invocation of the callback function (that is when first issue is processed) a direct ByteBuffer is allocated by the JVM. The callback function then performs only a non-expensive memcpy("Java ByteBuffer", "C struct ORTERecvInfo" , sizeof(ORTERecvInfo)) every-time new issue is received. The information stored in the ByteBuffer is then processed only when requested.

**Comment by Vajnar** [comment]
Drop the switch from Thumb to ARM for now as this callback commit is more important and GitHub doesn't allow me to create a new pull request because of the pending one.

**Comment by Vajnar** [comment]
Speed-up the subscriber callback by caching method IDs and by moving away run-once code.

**Comment by Vajnar** [comment]
Finally found time to do some performance comparison. I compared the state without this whole patch-set and with it.


Reception of 10,000 issues.

PC, Intel C2Q Q9550 @ 2GHz, OpenJDK 7
Before: 2.01 s
Now:     1.68 s

SE Xperia Ray, Android 4.1
Before (Thumb):  10.95 s
Before (ARM):      10.90 s
Now (Thumb):       9.43 s
Now (ARM):           9.53 s

The performance of Thumb-2 was a little bit better than ARM before this patch-set, but now the Thumb-2 mode outperforms the ARM mode.

**Comment by wentasah** [comment]
OK but AFAICS the original performance patch is no longer in the pull request so I cannot easily merge it. Please create a new pull request and put your benchamrk results into the commit message.

**Pull request closed without merging**
