### PR TITLE
Shape fixes

### PR DESCRIPTION
**Pull request by Vajnar**
@qeef Few fixes for shape_android. Please check, whether you agree with them.

### CODE REVIEW

**Comment by qeef** [comment]
Thanks a lot, I will check it as soon as possible (don't have android device at the moment).

I know that I had some difficulties with endianing and therefore I set ByteOrder statically, but I will definitely test it.

Thanks again

**Comment by Vajnar** [comment]
@qeef I forgot to commit one more change.

**Comment by wentasah** [comment]
On Sat, May 23 2015, Jiri Hubacek wrote:
> Thanks a lot, I will check it as soon as possible (don't have android
> device at the moment).
>
> I know that I had some difficulties with endianing and therefore I set
> ByteOrder statically, but I will definitely test it.

I think that Martin has already tested it. Can you just look at the code
and tell whether it looks good from your point of view?

**Comment by qeef** [comment]
I have no problem with changes, they look good.

The only reason I wanted to test it before, was changes in enforcing ByteOrder. I had some problems with sending coordinates without enforcing ByteOrder. However if it works, please, feel free to merge changes.

Thanks.

**Pull request merged**
