### PR TITLE
Migrate old and deprecated ADT build to new CMake/Gradle/Android Studio

### PR DESCRIPTION
**Pull request by Vajnar**
Since ADT for Eclipse was phased out by Google and replaced by CMake/Gradle/Android Studio (based on jIDEA), lets migrate RoboDruid and shape_android projects to it.

### CODE REVIEW

**Comment by ppisa** [comment]
Thanks for contribution/update. On basis of our phone call, I will wait for the confirmation/check that the steps are reproducible. Then I merge updates to the official mainline branches referenced by https://orte.sourceforge.net/

Developers with interest to continue on Jiří Hubáček's unfinished [switch to DDS version 2.x](https://wiki.control.fel.cvut.cz/mediawiki/images/3/37/Dp_2016_hubacek_jiri.pdf) are welcomed. I have some money left from [ESA project](https://gitlab.com/pikron/projects/sumintadc/deliverables) at my company ([PiKRON](https://pikron.com/)) so I can provide even some small funding. I have even some local fund from my teaching and projects at CTU [OTREES](https://gitlab.fel.cvut.cz/otrees/org/-/wikis/knowbase) so some stipends are possible too.

**Comment by wentasah** [comment]
Hi Martin,

I'm not sure whether this is related to some collaboration with Pavel or it is just your holiday relaxation activity :-). Personally, I have only a little interest in maintaining ORTE, as there are several much better and open-source implementations of the RTPS protocol. Some even support Android. We have successfully used [FastDDS to communicate between Android apps and other devices](https://github.com/CTU-IIG/ipa2x). Another reason is that ORTE contains hard to debug bugs (probably race conditions), which I tried to hunt on [my refactor branch](https://github.com/CTU-IIG/orte/compare/master...sojka/refactor), but it would require much more effort to complete.

If Pavel wants to maintain ORTE, I've no problem with it. You should only know that this repo (as well as [the SF one](https://sourceforge.net/p/orte/orte/ci/master/tree/)) is just an automatically synced mirror of the [primary repository at rtime](https://rtime.felk.cvut.cz/gitweb/orte.git). So if this PR is merged here, it will get overwritten by the mirror script. If this is merged to rtime, I think Github will detect this PR as merged (after the changes get mirrored here).

Otherwise, I can merge this too. Just let me know it's ready.

**Comment by ppisa** [comment]
The problem with [Fast-DDS](https://github.com/eProsima/Fast-DDS) is that it is relatively huge project and written in C++ which is not ideal for RTEMS and NuttX. The eProsima is aware of these problems and started [Safe-DDS](https://www.eprosima.com/index.php/products-all/eprosima-safe-dds) but as far as I know from their presentations and online meetings that is intended to be paid only proprietary licensed solution. It is still C++.  have feedback from RTEMS and NuttX community that they would be very glad for small C based open-source DDS solution and I am not aware of such alternative. As for the synchronization problems and switch to 2.x standard, I have invested considerable time to work and mentor work of Jiří Vlsák/Hubáček on code rewrite update in frame of his thesis and there has been promising results shown before you and IIG leadership forbid his continuation on the project when he was employed on another projects. If you know about some open-source DDS alternative suiting well needs of NuttX and RTEMS community then I agree that ORTE in not much interesting to invest. But I am not aware of such alternative and small embedded DDS would be interesting for example to be integrated into [pysimCoder](https://github.com/robertobucher/pysimCoder) which already aims for process data exchange with ROS based systems. For runtime tuning and service data exchange, we have integrated [Elektroline](https://www.elektroline.cz/)  developed open source [silicon-heaven](https://github.com/silicon-heaven/) protocol. The actual state of the project is demonstrated by Robots5 videos [https://www.youtube.com/@robots5](https://www.youtube.com/@robots5) as well as articles:

- [An Open-Source Python-Based Framework of Real-Time Controls as Flight Software of CubeSats](https://arc.aiaa.org/doi/abs/10.2514/6.2024-1663)
- [pysimCoder – Open-Source Rapid Control Prototyping for GNU/Linux and NuttX](https://ieeexplore.ieee.org/abstract/document/10217596)
- [Open-Source Based Remote Control of Thermo-Optical Plant uDAQ28/LT](https://link.springer.com/chapter/10.1007/978-3-031-56075-0_32)

and more.

**Comment by ppisa** [comment]
So DDS integration is next logical step.

**Comment by wentasah** [comment]
On Wed, Jul 17 2024, Pavel Pisa wrote:
> It is still C++. have feedback from RTEMS and NuttX community that
> they would be very glad for small C based open-source DDS solution and
> I am not aware of such alternative.

I know only about cyclonedds. It seems to support Zephyr and FreeRTOS so
it might be suitable for your targets as well.

**Comment by Vajnar** [comment]
Hi @wentasah, out of curiosity (holiday relaxation), I tried installing RoboDruid from [dspace.cvut.cz](https://dspace.cvut.cz/handle/10467/61469) and it didn't work. I investigated a little and found out old apps [are not allowed](https://developer.android.com/about/versions/14/behavior-changes-all#minimum-target-api-level) to be installed on Android 14. Then I found out the old Android Development Tools for Eclipse are no longer supported by Google, thus the migration. This was my motivation. For the sake of completeness I also migrated shape_android. With the changes in this PR, it is possible to install resulting APKs on Android 11+.

**Comment by Vajnar** [comment]
Otherwise build is reproducible, so should be ready for merge.

**Comment by ppisa** [comment]
Thanks, pushed to the master.

**Pull request merged**
